
# Shared supervisor config
x-supervisor-common-config: &supervisor_common
  image: wasmiot/supervisor-base:local
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    interval: 90s
    timeout: 30s
    retries: 3
    start_period: 30s
  privileged: true
  devices:
    - /dev/video0:/dev/video0
  # depends_on:
  #   wasmiot-orchestrator:
  #     condition: service_healthy

services:
  
  # Orchestrator service (Rust)
  wasmiot-orchestrator:
    tty: true
    container_name: test-env-orchestrator
    build:
      context: orchestrator-rust-port
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        PORT: ${PORT}
    ports:
      - "${PUBLIC_PORT}:${PUBLIC_PORT}"
    env_file: .env
    networks:
      default:
        ipv4_address: 172.20.0.10
    volumes:
      - type: bind
        source: ./instance/orchestrator/files
        target: /app/build/files
      - type: bind
        source: ./instance/orchestrator/init
        target: /app/build/init
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${PUBLIC_HOST}:${PUBLIC_PORT}/health"]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    networks:
      default:
        ipv4_address: 172.20.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-test-config:/data/configdb
      - mongo-test-db:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MONGO_EXPRESS_PORT}:8081"
    networks:
      default:
        ipv4_address: 172.20.0.30
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  supervisor-image:
    tty: true
    profiles:
      - ABSTRACT_BASE_HACK_DO_NOT_USE
    image: wasmiot/supervisor-base:local
    build:
      context: ./rust-supervisor
      dockerfile: Dockerfile

  supervisor1:
    <<: *supervisor_common
    container_name: test-env-supervisor-1
    environment:
      - DEFAULT_CAMERA_DEVICE=0
      - SUPERVISOR_NAME=rust-supervisor-1
      - WASMIOT_SUPERVISOR_PORT=8080
      - EXTERNAL_LOGGING_ENABLED=true
      - WASMIOT_LOGGING_ENDPOINT=http://172.20.0.10:${PUBLIC_PORT}/device/logs
    volumes:
      - type: bind
        source: ./instance/supervisor-1/configs
        target: /app/instance/configs
      - type: bind
        source: ./instance/supervisor-1/outputs
        target: /app/instance/outputs
      - type: bind
        source: ./instance/supervisor-1/wasm-modules
        target: /app/instance/wasm-modules
      - type: bind
        source: ./instance/supervisor-1/wasm-params
        target: /app/instance/wasm-params
    networks:
      default:
        ipv4_address: 172.20.0.40
    ports:
      - 3002:8080

  supervisor2:
    <<: *supervisor_common
    container_name: test-env-supervisor-2
    environment:
      - DEFAULT_CAMERA_DEVICE=0
      - SUPERVISOR_NAME=rust-supervisor-2
      - WASMIOT_SUPERVISOR_PORT=8080
      - EXTERNAL_LOGGING_ENABLED=true
      - WASMIOT_LOGGING_ENDPOINT=http://172.20.0.10:${PUBLIC_PORT}/device/logs
    volumes:
      - type: bind
        source: ./instance/supervisor-2/configs
        target: /app/instance/configs
      - type: bind
        source: ./instance/supervisor-2/outputs
        target: /app/instance/outputs
      - type: bind
        source: ./instance/supervisor-2/wasm-modules
        target: /app/instance/wasm-modules
      - type: bind
        source: ./instance/supervisor-2/wasm-params
        target: /app/instance/wasm-params
    networks:
      default:
        ipv4_address: 172.20.0.50
    ports:
      - 3003:8080

volumes:
  mongo-test-config:
  mongo-test-db:

networks:
  default:
    name: wasmiot-test-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
