services:
  # Orchestrator base service
  orchestrator-base:
    container_name: wasmiot-orchestrator
    build:
      context: wasmiot-orchestrator/fileserv
      dockerfile: ./Dockerfile
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    networks:
      default:
        ipv4_address: 172.15.0.10
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      WASMIOT_INIT_FOLDER: ${WASMIOT_INIT_FOLDER:-/init}
      WASMIOT_CLEAR_LOGS: ${WASMIOT_CLEAR_LOGS:-true}
    volumes:
      - ../init:/init
    command: nodejs ./server.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Database service
  mongo:
    image: mongo:6.0.15
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.15.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/data/configdb
      - mongo-db:/data/db

  # Orchestrator webgui
  webgui:
    build:
      context: ./orchestrator-webgui
      dockerfile: js.Dockerfile
    ports:
      - 3313:3313
    environment:
      - PORT=3313
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      default:
        ipv4_address: 172.15.0.19
    depends_on:
      orchestrator-base:
        condition: service_healthy

  # Supervisor Base Service
  device-base:
    profiles:
      - ABSTRACT_BASE_HACK_DO_NOT_USE
    build:
      context: ./rust-supervisor
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  # Supervisor Instances
  raspi1:
    extends: device-base
    profiles:
      - device
    environment:
      - WASMIOT_ORCHESTRATOR_URL=http://wasmiot-orchestrator:3000
      - WASMIOT_LOGGING_ENDPOINT=http://wasmiot-orchestrator:3000/device/logs
      - WASMIOT_SUPERVISOR_IP=172.15.0.21
      - SUPERVISOR_NAME=rust-supervisor-1
      - DEFAULT_CAMERA_DEVICE=0
      - DEFAULT_URL_SCHEME=http
      - DEVICE_TYPE=RaspberryPi-with-camera
      - WASMIOT_SUPERVISOR_PORT=8080
      - EXTERNAL_LOGGING_ENABLED=true
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - WASM_RUNTIME=wasmtime
    ports:
      - 3001:8080
    privileged: true
    volumes:
      - ./devices/raspi1/configs:/app/instance/configs
      - ./devices/raspi1/modules:/app/instance/modules
      - ./devices/raspi1/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.21
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      orchestrator-base:
        condition: service_healthy

  raspi2:
    extends: device-base
    profiles:
      - device
    environment:
      - WASMIOT_ORCHESTRATOR_URL=http://wasmiot-orchestrator:3000
      - WASMIOT_LOGGING_ENDPOINT=http://wasmiot-orchestrator:3000/device/logs
      - WASMIOT_SUPERVISOR_IP=172.15.0.22
      - SUPERVISOR_NAME=rust-supervisor-2
      - DEFAULT_CAMERA_DEVICE=0
      - DEFAULT_URL_SCHEME=http
      - DEVICE_TYPE=RaspberryPi-with-camera
      - WASMIOT_SUPERVISOR_PORT=8080
      - EXTERNAL_LOGGING_ENABLED=true
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - WASM_RUNTIME=wasmtime
    ports:
      - 3002:8080
    privileged: true
    volumes:
      - ./devices/raspi2/configs:/app/instance/configs
      - ./devices/raspi2/modules:/app/instance/modules
      - ./devices/raspi2/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.22
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      orchestrator-base:
        condition: service_healthy

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
