services:
  # Orchestrator base service
  orchestrator-base:
    container_name: wasmiot-orchestrator
    build:
      context: wasmiot-orchestrator/fileserv
      dockerfile: ./Dockerfile
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    networks:
      default:
        ipv4_address: 172.15.0.10
    environment:
      MONGO_HOST: ${MONGO_HOST:-mongo}
      MONGO_PORT: ${MONGO_PORT:-27017}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      WASMIOT_INIT_FOLDER: ${WASMIOT_INIT_FOLDER:-/init}
      WASMIOT_CLEAR_LOGS: ${WASMIOT_CLEAR_LOGS:-true}
    volumes:
      - ../init:/init
    command: nodejs ./server.js

  # Database service
  mongo:
    image: mongo:6.0.15
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.15.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: mongod --port ${MONGO_PORT:-27017}
    volumes:
      - mongo-config:/data/configdb
      - mongo-db:/data/db

  # Supervisor Base Service
  device-base:
    profiles:
      - ABSTRACT_BASE_HACK_DO_NOT_USE
    image: ghcr.io/liquidai-project/wasmiot-supervisor
    volumes:
      - type: bind
        source: ./wasmiot-supervisor/host_app
        target: /app/host_app
    env_file:
      - .env
    # links:
    #   - orchestrator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  # Supervisor Instances
  raspi1:
    extends: device-base
    profiles:
      - device
    environment:
      - DEVICE_TYPE=RaspberryPi-with-camera
      - FLASK_APP=raspi1
      - WASMIOT_SUPERVISOR_IP=172.15.0.21
    ports:
      - 3001:5000
    privileged: true
    volumes:
      - ./devices/raspi1/configs:/app/instance/configs
      - ./devices/raspi1/modules:/app/instance/modules
      - ./devices/raspi1/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.21

  raspi2:
    extends: device-base
    profiles:
      - device
    environment:
      - DEVICE_TYPE=RaspberryPi-with-camera
      - FLASK_APP=raspi2
      - WASMIOT_SUPERVISOR_IP=172.15.0.22
    ports:
      - 3002:5000
    privileged: true
    volumes:
      - ./devices/raspi2/configs:/app/instance/configs
      - ./devices/raspi2/modules:/app/instance/modules
      - ./devices/raspi2/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.22
    devices:
      - /dev/video0:/dev/video0

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
